### ISSUE TITLE
Style for unavailable sku's

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/product-details#140]
**Is your feature request related to a problem? Please describe.**
At this time it is not possible to style the text from the unavailable options.

**Describe alternatives you've considered**
Instead of that div to which the diagonalCross class is added, a class can be added to the main div that holds the option.

**Comment by klzns** [comment]
Hi @khrizzcristian this app is deprecated. There are better alternatives to build PDP now. We created more low level blocks that make it easier to build it.

You can check the [store-theme product page as an example](https://github.com/vtex-apps/store-theme/blob/master/store/blocks/product.jsonc).
